# Generated by Django 3.2.5 on 2021-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('contents', models.CharField(max_length=1000)),
                ('major', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('contents', models.CharField(max_length=1000)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('MBTI', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=300)),
            ],
        ),
    ]
